### ISSUE TITLE
Prevent Sensitive Data Exposure

### ISSUE THREAD

**Issue by Dynna** [Dynna/PBL#17]
- Classify data processed, stored, or transmitted by an application;
- Identify which data is sensitive according to privacy laws, regulatory requirements, or business needs;
- Apply controls as per the classification;
- Don’t store sensitive data unnecessarily;
- Discard it as soon as possible or use PCI DSS compliant tokenization or even truncation. Data that is not retained cannot be stolen;
- Make sure to encrypt all sensitive data at rest;
- Ensure up-to-date and strong standard algorithms, protocols, and keys are in place; use proper key management;
- Encrypt all data in transit with secure protocols such as TLS with perfect forward secrecy (PFS) ciphers, cipher prioritization by the server, and secure parameters;
- Enforce encryption using directives like HTTP Strict Transport Security (HSTS);
- Disable caching for responses that contain sensitive data;
- Store passwords using strong adaptive and salted hashing functions with a work factor (delay factor), such as Argon2, scrypt, bcrypt, or PBKDF2;
- Verify independently the effectiveness of configuration and settings.
-

**Comment by ecaterinagherbovei** [comment]
* we encrypted passwords
* we forcing an HTTPS with a middleware (Middleware provides a convenient mechanism for filtering HTTP requests entering your application. This will check if the request is secure, if it is not secure, it will redirect the user to the secure/https URL.)
   - we created new middleware in app/Http/Middleware/HttpsProtocolMiddleware

![Screenshot (1)](https://user-images.githubusercontent.com/55796198/101631251-bb489400-3a2c-11eb-9ce2-e8834dada5b0.png)
