### ISSUE TITLE
Security Misconfiguration

### ISSUE THREAD

**Issue by Dynna** [Dynna/PBL#27]
- [x] Keep all server software and any dependencies in your web application up to date.
- [x] Disable directory listing for your web server.
- [x] Disable debugging on production servers. Even on staging servers, debugging can reveal sensitive server information by outputting all your environment variables. Make use of the debug_hide app configuration option in Laravel to prevent this.

**Comment by ecaterinagherbovei** [comment]
![collaid – app php 12_9_2020 4_52_55 PM](https://user-images.githubusercontent.com/55796198/101645454-11263780-3a3f-11eb-8988-8acc2925ea3d.png)
debug is set tu false that means it is disabled
